export { QuieleHeroInfoSection } from "@/modules/quiele/sections/quiele-hero-info-section";
export { QuieleMarqueeMissionSection } from "@/modules/quiele/sections/quiele-marquee-mission-section";
export { QuieleStatsJourneySection } from "@/modules/quiele/sections/quiele-stats-journey-section";
export { QuieleFeatureSplitSection } from "@/modules/quiele/sections/quiele-feature-split-section";
export { QuieleServiceStepperSection } from "@/modules/quiele/sections/quiele-service-stepper-section";
export { QuieleAdvantagesSection } from "@/modules/quiele/sections/quiele-advantages-section";
export { QuieleServicesGridSection } from "@/modules/quiele/sections/quiele-services-grid-section";
export { QuieleTeamShowcaseSection } from "@/modules/quiele/sections/quiele-team-showcase-section";
export { QuieleHistoryTimelineSection } from "@/modules/quiele/sections/quiele-history-timeline-section";
